target-version = "py310"
line-length = 120

[lint]
select = ["E", "F", "I", "N", "W", "UP", "D"]
ignore = ["D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107", "D200", "D205", "D400", "D401", "D402", "D415"]

[format]
quote-style = "double"
